### ISSUE TITLE
Adding version 1.31

### ISSUE THREAD

**Issue by ngoctienvt** [Qyperion/WC3LanGame#2]
I’m trying to play LAN online with friends. But our version is 1.31.

Could you help to update it to work with the version we use.

https://drive.google.com/file/d/1L3H2U7S4X3LxDZpHM0sYINtbzjcC6B5V/view?usp=sharing

here is our warcraft version. Thank you so much.

**Comment by Qyperion** [comment]
For WC3, you do not need this program anymore. Blizzard integrated Bonjour Service in the last versions of WC3, allowing automatic discovery of hosted WC3 games on a local network.
