### ISSUE TITLE
Possible to forward all broadcast traffic instead of only that of wc3?

### ISSUE THREAD

**Issue by Coolykoen** [Qyperion/WC3LanGame#3]
Would it be possible? i would love to use this on other games that also use broadcast traffic to find lan clients.
If not, understandable :)

**Comment by Qyperion** [comment]
Unfortunately, no.

This program does not just forward traffic but sends its packets (according to Warcraft 3 LAN game network protocol) to find active games and extract information about them. Moreover, this program modifies the network port in some packets for correct operation.
Therefore, this program is created specifically for Warcraft 3 and cannot be used for other games.

If you want to play over a local network with remote players, then I can recommend [ZeroTier](https://github.com/zerotier/ZeroTierOne) to create a virtual local network. If there is a problem with a specific game over ZeroTier, then [here](https://docs.zerotier.com/windows-lan-game/) is a possible solution to this problem.

**Comment by Coolykoen** [comment]
Thank you so much for your reply, i appreciate it very much :)

I see, that makes a lot of sense. We did try Tailscale, but it does NOT do broadcast traffic. Ill have to look into that article more, thanks for sharing it!
